default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV['DB_POOL'] || 25 %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default
  database: docuseal_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: docuseal_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  sslmode: <%= ENV['DB_SSLMODE'] %>
  sslrootcert: <%= ENV['DB_SSLCERT'] %>

staging:
  <<: *default
  sslmode: <%= ENV['DB_SSLMODE'] %>
  sslrootcert: <%= ENV['DB_SSLCERT'] %>
  variables:
    statement_timeout: 120000
