disk:
  service: Disk
  root: <%= ENV['WORKDIR'] || '.' %>/attachments
  public: true

aws_s3:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  bucket: <%= ENV['S3_ATTACHMENTS_BUCKET'] %>
  public: <%= ENV['ACTIVE_STORAGE_PUBLIC'] == 'true' %>
  upload:
    cache_control: 'public, max-age=31536000'

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
  public: true
